name: 坛子
url: http://kelyau.github.io
description: 坛子的github page

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']